imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
    tests:
        before:
          - 'cp .env.scrutinizer .env'
          - 'php artisan migrate --force ---v'
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"